version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: wiki
      MYSQL_PASSWORD: DEP@ssw0rd
    volumes:
      - dbvolume:/var/lib/mysql

  wiki:
    image: mediawiki
    container_name: wiki
    restart: always
    ports:
      - "8080:80"
    environment:
      MEDIAWIKI_DB_HOST: db
      MEDIAWIKI_DB_USER: wiki
      MEDIAWIKI_DB_PASSWORD: DEP@ssw0rd
      MEDIAWIKI_DB_NAME: mediawiki
    volumes:
      - ./LocalSettings.php:/var/www/html/LocalSettings.php

volumes:
  dbvolume:
