version: '3.7'

services:
  wiki:
    image: mediawiki
    ports:
      - "8080:80"
    volumes:
      - ~/LocalSettings.php:/var/www/html/LocalSettings.php
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: wiki
      MYSQL_PASSWORD: DEP@ssw0rd
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - dbvolume:/var/lib/mysql

volumes:
  dbvolume:
